services:
  postgres:
    image: postgres:17-alpine
    container_name: insider-one-postgres
    environment:
      POSTGRES_DB: insider_one_assessment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d insider_one_assessment"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: insider-one-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: insider-one-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: insider-one-redisinsight
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - redisinsight_data:/data

  jaeger:
    image: jaegertracing/all-in-one:1.67.0
    container_name: insider-one-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4318:4318"

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: insider-one-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./infra/pgadmin/servers.json:/pgadmin4/servers.json:ro

  migrate:
    image: migrate/migrate:v4.18.3
    container_name: insider-one-migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations:ro
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/insider_one_assessment?sslmode=disable",
        "up"
      ]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insider-one-api
    command: ["/usr/local/bin/api"]
    environment:
      HTTP_PORT: ":8080"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/insider_one_assessment?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      PROVIDER_URL: "https://webhook.site/37eaaf61-d98a-4eeb-9ec0-a095794b527b"
      PROVIDER_TIMEOUT: "5s"
      PROVIDER_MOCK_RESPONSE: ""
      CHANNEL_RATE_LIMIT: "100"
      LOG_LEVEL: "debug"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      jaeger:
        condition: service_started
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    command: ["/usr/local/bin/worker"]
    environment:
      HTTP_PORT: ":8080"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/insider_one_assessment?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_URL: "redis:6379"
      PROVIDER_URL: "https://webhook.site/37eaaf61-d98a-4eeb-9ec0-a095794b527b"
      PROVIDER_TIMEOUT: "5s"
      CHANNEL_RATE_LIMIT: "100"
      LOG_LEVEL: "debug"
      PROVIDER_MOCK_RESPONSE: ""
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      jaeger:
        condition: service_started

volumes:
  postgres_data:
  rabbitmq_data:
  pgadmin_data:
  redisinsight_data: