// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/notification.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	request "insider-one-assessment/internal/dto/request"
	model "insider-one-assessment/internal/model"
	repository "insider-one-assessment/internal/repository"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockINotificationRepository is a mock of INotificationRepository interface.
type MockINotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockINotificationRepositoryMockRecorder
}

// MockINotificationRepositoryMockRecorder is the mock recorder for MockINotificationRepository.
type MockINotificationRepositoryMockRecorder struct {
	mock *MockINotificationRepository
}

// NewMockINotificationRepository creates a new mock instance.
func NewMockINotificationRepository(ctrl *gomock.Controller) *MockINotificationRepository {
	mock := &MockINotificationRepository{ctrl: ctrl}
	mock.recorder = &MockINotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotificationRepository) EXPECT() *MockINotificationRepositoryMockRecorder {
	return m.recorder
}

// CancelNotification mocks base method.
func (m *MockINotificationRepository) CancelNotification(ctx context.Context, id string, cancelledAt time.Time) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelNotification", ctx, id, cancelledAt)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelNotification indicates an expected call of CancelNotification.
func (mr *MockINotificationRepositoryMockRecorder) CancelNotification(ctx, id, cancelledAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelNotification", reflect.TypeOf((*MockINotificationRepository)(nil).CancelNotification), ctx, id, cancelledAt)
}

// ClaimDueOutboxEvents mocks base method.
func (m *MockINotificationRepository) ClaimDueOutboxEvents(ctx context.Context, limit int) ([]repository.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDueOutboxEvents", ctx, limit)
	ret0, _ := ret[0].([]repository.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDueOutboxEvents indicates an expected call of ClaimDueOutboxEvents.
func (mr *MockINotificationRepositoryMockRecorder) ClaimDueOutboxEvents(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDueOutboxEvents", reflect.TypeOf((*MockINotificationRepository)(nil).ClaimDueOutboxEvents), ctx, limit)
}

// CreateNotification mocks base method.
func (m *MockINotificationRepository) CreateNotification(ctx context.Context, idempotencyKey, requestHash string, item request.NotificationItem) (*model.Notification, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, idempotencyKey, requestHash, item)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockINotificationRepositoryMockRecorder) CreateNotification(ctx, idempotencyKey, requestHash, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockINotificationRepository)(nil).CreateNotification), ctx, idempotencyKey, requestHash, item)
}

// CreateNotifications mocks base method.
func (m *MockINotificationRepository) CreateNotifications(ctx context.Context, params repository.CreateNotificationsParams) (model.NotificationBatch, []model.Notification, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotifications", ctx, params)
	ret0, _ := ret[0].(model.NotificationBatch)
	ret1, _ := ret[1].([]model.Notification)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateNotifications indicates an expected call of CreateNotifications.
func (mr *MockINotificationRepositoryMockRecorder) CreateNotifications(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotifications", reflect.TypeOf((*MockINotificationRepository)(nil).CreateNotifications), ctx, params)
}

// CreateTemplate mocks base method.
func (m *MockINotificationRepository) CreateTemplate(ctx context.Context, template model.MessageTemplate) (model.MessageTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, template)
	ret0, _ := ret[0].(model.MessageTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockINotificationRepositoryMockRecorder) CreateTemplate(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockINotificationRepository)(nil).CreateTemplate), ctx, template)
}

// DeleteTemplate mocks base method.
func (m *MockINotificationRepository) DeleteTemplate(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockINotificationRepositoryMockRecorder) DeleteTemplate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockINotificationRepository)(nil).DeleteTemplate), ctx, id)
}

// GetBatchByID mocks base method.
func (m *MockINotificationRepository) GetBatchByID(ctx context.Context, id string) (*model.NotificationBatch, []model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatchByID", ctx, id)
	ret0, _ := ret[0].(*model.NotificationBatch)
	ret1, _ := ret[1].([]model.Notification)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBatchByID indicates an expected call of GetBatchByID.
func (mr *MockINotificationRepositoryMockRecorder) GetBatchByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatchByID", reflect.TypeOf((*MockINotificationRepository)(nil).GetBatchByID), ctx, id)
}

// GetNotificationByID mocks base method.
func (m *MockINotificationRepository) GetNotificationByID(ctx context.Context, id string) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationByID", ctx, id)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationByID indicates an expected call of GetNotificationByID.
func (mr *MockINotificationRepositoryMockRecorder) GetNotificationByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationByID", reflect.TypeOf((*MockINotificationRepository)(nil).GetNotificationByID), ctx, id)
}

// GetTemplateByID mocks base method.
func (m *MockINotificationRepository) GetTemplateByID(ctx context.Context, id string) (model.MessageTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByID", ctx, id)
	ret0, _ := ret[0].(model.MessageTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateByID indicates an expected call of GetTemplateByID.
func (mr *MockINotificationRepositoryMockRecorder) GetTemplateByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByID", reflect.TypeOf((*MockINotificationRepository)(nil).GetTemplateByID), ctx, id)
}

// ListNotifications mocks base method.
func (m *MockINotificationRepository) ListNotifications(ctx context.Context, params repository.ListNotificationsParams) ([]model.Notification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, params)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockINotificationRepositoryMockRecorder) ListNotifications(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockINotificationRepository)(nil).ListNotifications), ctx, params)
}

// ListTemplates mocks base method.
func (m *MockINotificationRepository) ListTemplates(ctx context.Context, channel *model.NotificationChannel) ([]model.MessageTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx, channel)
	ret0, _ := ret[0].([]model.MessageTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockINotificationRepositoryMockRecorder) ListTemplates(ctx, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockINotificationRepository)(nil).ListTemplates), ctx, channel)
}

// MarkNotificationFailed mocks base method.
func (m *MockINotificationRepository) MarkNotificationFailed(ctx context.Context, id string, attemptResult repository.NotificationAttemptResult, failedAt time.Time) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationFailed", ctx, id, attemptResult, failedAt)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationFailed indicates an expected call of MarkNotificationFailed.
func (mr *MockINotificationRepositoryMockRecorder) MarkNotificationFailed(ctx, id, attemptResult, failedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationFailed", reflect.TypeOf((*MockINotificationRepository)(nil).MarkNotificationFailed), ctx, id, attemptResult, failedAt)
}

// MarkNotificationSent mocks base method.
func (m *MockINotificationRepository) MarkNotificationSent(ctx context.Context, id string, attemptResult repository.NotificationAttemptResult, providerMessageID string, sentAt time.Time) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationSent", ctx, id, attemptResult, providerMessageID, sentAt)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationSent indicates an expected call of MarkNotificationSent.
func (mr *MockINotificationRepositoryMockRecorder) MarkNotificationSent(ctx, id, attemptResult, providerMessageID, sentAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationSent", reflect.TypeOf((*MockINotificationRepository)(nil).MarkNotificationSent), ctx, id, attemptResult, providerMessageID, sentAt)
}

// MarkOutboxEventPublished mocks base method.
func (m *MockINotificationRepository) MarkOutboxEventPublished(ctx context.Context, eventID, notificationID string, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxEventPublished", ctx, eventID, notificationID, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOutboxEventPublished indicates an expected call of MarkOutboxEventPublished.
func (mr *MockINotificationRepositoryMockRecorder) MarkOutboxEventPublished(ctx, eventID, notificationID, publishedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxEventPublished", reflect.TypeOf((*MockINotificationRepository)(nil).MarkOutboxEventPublished), ctx, eventID, notificationID, publishedAt)
}

// ScheduleNotificationRetry mocks base method.
func (m *MockINotificationRepository) ScheduleNotificationRetry(ctx context.Context, id string, attemptResult repository.NotificationAttemptResult, nextAttemptAt time.Time) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleNotificationRetry", ctx, id, attemptResult, nextAttemptAt)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScheduleNotificationRetry indicates an expected call of ScheduleNotificationRetry.
func (mr *MockINotificationRepositoryMockRecorder) ScheduleNotificationRetry(ctx, id, attemptResult, nextAttemptAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleNotificationRetry", reflect.TypeOf((*MockINotificationRepository)(nil).ScheduleNotificationRetry), ctx, id, attemptResult, nextAttemptAt)
}

// StartProcessingNotification mocks base method.
func (m *MockINotificationRepository) StartProcessingNotification(ctx context.Context, id string, startedAt time.Time) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartProcessingNotification", ctx, id, startedAt)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartProcessingNotification indicates an expected call of StartProcessingNotification.
func (mr *MockINotificationRepositoryMockRecorder) StartProcessingNotification(ctx, id, startedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcessingNotification", reflect.TypeOf((*MockINotificationRepository)(nil).StartProcessingNotification), ctx, id, startedAt)
}
